$(document).ready(function(){
  $('#img1').mouseenter(function(){
  //  $(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img2").addClass("blur");
    $("#img3").addClass("blur");
    $("#img4").addClass("blur");
    $("#img5").addClass("blur");
    $("#img6").addClass("blur");
  });
  $('#img1').mouseleave(function(){
  //  $(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img2').removeClass("blur");
    $("#img3").removeClass("blur");
    $('#img4').removeClass("blur");
    $('#img5').removeClass("blur");
    $('#img6').removeClass("blur");
  });
  $('#img2').mouseenter(function(){
  //  $(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img1").addClass("blur");
    $("#img3").addClass("blur");
    $("#img4").addClass("blur");
    $("#img5").addClass("blur");
    $("#img6").addClass("blur");
  });
  $('#img2').mouseleave(function(){
  //  $(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img1').removeClass("blur");
    $("#img3").removeClass("blur");
    $('#img4').removeClass("blur");
    $('#img5').removeClass("blur");
    $('#img6').removeClass("blur");
  });
  $('#img3').mouseenter(function(){
    //$(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img1").addClass("blur");
    $("#img2").addClass("blur");
    $("#img4").addClass("blur");
    $("#img5").addClass("blur");
    $("#img6").addClass("blur");
  });
  $('#img3').mouseleave(function(){
    //$(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img1').removeClass("blur");
    $("#img2").removeClass("blur");
    $('#img4').removeClass("blur");
    $('#img5').removeClass("blur");
    $('#img6').removeClass("blur");
  });
  $('#img4').mouseenter(function(){
  //  $(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img1").addClass("blur");
    $("#img2").addClass("blur");
    $("#img3").addClass("blur");
    $("#img5").addClass("blur");
    $("#img6").addClass("blur");
  });
  $('#img4').mouseleave(function(){
    //$(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img1').removeClass("blur");
    $("#img2").removeClass("blur");
    $('#img3').removeClass("blur");
    $('#img5').removeClass("blur");
    $('#img6').removeClass("blur");
  });
  $('#img5').mouseenter(function(){
    //$(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img1").addClass("blur");
    $("#img2").addClass("blur");
    $("#img3").addClass("blur");
    $("#img4").addClass("blur");
    $("#img6").addClass("blur");
  });
  $('#img5').mouseleave(function(){
    //$(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img1').removeClass("blur");
    $("#img2").removeClass("blur");
    $('#img3').removeClass("blur");
    $('#img4').removeClass("blur");
    $('#img6').removeClass("blur");
  });
  $('#img6').mouseenter(function(){
    //$(this).css('z-index','1');
    $(this).css('transform','scale(1.1,1.1)');
    $("#img1").addClass("blur");
    $("#img2").addClass("blur");
    $("#img3").addClass("blur");
    $("#img4").addClass("blur");
    $("#img5").addClass("blur");
  });
  $('#img6').mouseleave(function(){
    //$(this).css('z-index','0');
    $(this).css('transform','scale(1,1)');
    $('#img1').removeClass("blur");
    $("#img2").removeClass("blur");
    $('#img3').removeClass("blur");
    $('#img4').removeClass("blur");
    $('#img5').removeClass("blur");
  });
});
